server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://atomscat-oauth-mysql:3306/atomscat-oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa123456
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# 日志
logging:
  file: /data/logs/app.log