server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atomscat-oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: Aa123456
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none

  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Swagger界面内容配置
swagger:
  title: com.atomscat-oauth-API接口文档
  description: com.atomscat-oauth Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://oauth.com.atomscat.com
  contact:
    name: Howell Yang
    url: http://blog.com.atomscat.com
    email: com.atomscat@qq.com

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

Atomscat:
  token:
    # 默认JWT 启用Redis后设置为true后，token将存入redis，并具有单点登录功能
    redis: true
    # token过期时间（分钟）
  tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
    # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10

# 日志
logging:
  file: com.atomscat-oauth/app.log