apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: cluster
spec:
  ports:
    - name: zoo1-2181
      port: 2181
      targetPort: 2181
    - name: zoo1-2888
      port: 2888
      targetPort: 2888
    - name: zoo1-3888
      port: 3888
      targetPort: 3888
  selector:
    app: zoo1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zoo2
  namespace: cluster
spec:
  ports:
    - name: zoo2-2181
      port: 2181
      targetPort: 2181
    - name: zoo2-2888
      port: 2888
      targetPort: 2888
    - name: zoo2-3888
      port: 3888
      targetPort: 3888
  selector:
    app: zoo2
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zoo3
  namespace: cluster
spec:
  ports:
    - name: zoo3-2181
      port: 2181
      targetPort: 2181
    - name: zoo3-2888
      port: 2888
      targetPort: 2888
    - name: zoo3-3888
      port: 3888
      targetPort: 3888
  selector:
    app: zoo3
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo1
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: zoo1
  replicas: 1 # by default is 1
  serviceName: zoo1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      hostname: zoo1
      containers:
        - name: zoo1
          image: zookeeper:latest
          ports:
            - containerPort: 2181
              name: zoo1-2181
            - containerPort: 2888
              name: zoo1-2888
            - containerPort: 3888
              name: zoo1-3888
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: "server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo2
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: zoo2
  replicas: 1 # by default is 1
  serviceName: zoo2
  template:
    metadata:
      labels:
        app: zoo2
    spec:
      hostname: zoo2
      containers:
        - name: zoo2
          image: zookeeper:latest
          ports:
            - containerPort: 2181
              name: zoo2-2181
            - containerPort: 2888
              name: zoo2-2888
            - containerPort: 3888
              name: zoo2-3888
          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: "server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo3
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: zoo3
  replicas: 1 # by default is 1
  serviceName: zoo3
  template:
    metadata:
      labels:
        app: zoo3
    spec:
      hostname: zoo3
      containers:
        - name: zoo3
          image: zookeeper:latest
          ports:
            - containerPort: 2181
              name: zoo3-2181
            - containerPort: 2888
              name: zoo3-2888
            - containerPort: 3888
              name: zoo3-3888
          env:
            - name: ZOO_MY_ID
              value: "3"
            - name: ZOO_SERVERS
              value: "server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888"